### ISSUE TITLE
Feature request: Smart cursor positioning

### ISSUE THREAD

**Issue by hafizrahman** [senff/Zendesk-markdown-buttons#3]
First off, nice work.

I tested this and found that in my case, each time I use a button, the focus and cursor on the textbox is lost. I had to click the textbox again to get back to writing.

This sounds absolutely lazy, I understand, but it would help with my flow if I can click the icon and then the cursor is transported back to where the new Markdown element was added, so I can then type right away.

Extra awesomeness bonus if the cursor positioning is smart, e.g: click the B button and have the cursor placed right in between `**` and `**`. This is how the editor in Github works as well.

**Comment by senff** [comment]
It does work like that for me in Firefox. Not in Chrome though, is that what you're using?

**Comment by senff** [comment]
Actually, this should be fixed now.
